[versions]
agp = "8.10.0"
appcompatVersion = "1.7.0"
browser = "1.9.0"
constraintlayoutVersion = "2.2.0"
coreKtx = "1.16.0"
gson = "2.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
preference = "1.2.1"
taptargetview = "1.15.0"

[libraries]
appcompat-v170 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
browser = { module = "androidx.browser:browser", version.ref = "browser" }
constraintlayout-v220 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
taptargetview = { module = "com.getkeepsafe.taptargetview:taptargetview", version.ref = "taptargetview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

